# Generated by Django 5.0 on 2023-12-06 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserSubscriber",
            new_name="Subscriber",
        ),
    ]
