# Generated by Django 5.0 on 2023-12-06 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_subscriber_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriber",
            old_name="email",
            new_name="Subscriber",
        ),
    ]
