# Generated by Django 5.0 on 2023-12-06 21:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_rename_email_subscriber_subscriber"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriber",
            old_name="Subscriber",
            new_name="email",
        ),
    ]
